# Generated by Django 5.0.4 on 2024-08-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_business', models.CharField(max_length=33)),
                ('phone_of_business', models.CharField(max_length=11)),
                ('address_of_business', models.CharField(max_length=100)),
                ('phrase_of_business', models.CharField(max_length=100)),
                ('email_of_business', models.CharField(max_length=33)),
            ],
        ),
    ]
