# Generated by Django 5.0.4 on 2024-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0002_alter_webdetails_phrase_of_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdetails',
            name='maplink',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
