# Generated by Django 5.0.4 on 2024-09-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0003_webdetails_maplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdetails',
            name='logo_of_business',
            field=models.ImageField(blank=True, null=True, upload_to='webcms'),
        ),
    ]
