# Generated by Django 5.1 on 2024-10-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0004_webdetails_logo_of_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials')),
                ('client_name', models.CharField(max_length=33)),
                ('testimonial_text', models.CharField(max_length=10)),
            ],
        ),
    ]
