# Generated by Django 5.1 on 2024-10-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0005_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_text',
            field=models.CharField(max_length=100),
        ),
    ]
