# Generated by Django 5.1 on 2024-11-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0006_alter_testimonial_testimonial_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_image', models.ImageField(upload_to='landing_images')),
                ('landing_title', models.CharField(max_length=100)),
                ('landing_caption', models.CharField(max_length=100)),
                ('landing_link', models.CharField(max_length=100)),
            ],
        ),
    ]
