# Generated by Django 5.1 on 2024-11-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcms', '0007_landingcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='landing_btn_text',
            field=models.CharField(default='Order Now', max_length=100),
            preserve_default=False,
        ),
    ]
